{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.5.0-SNAPSHOT/kotlinx-serialization-protobuf-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf.klib",
          "url": "kotlinx-serialization-protobuf-native-1.5.0-SNAPSHOT.klib",
          "size": 119326,
          "sha512": "488187bd8f3b2a17f91b98bbf131ba3cfa4e53ae1f059afd3dc6e4bfb106d711ac1cb491bbb12767c2a03339d18fe60740ec16f02076a4a9bd9ee23a35e2890a",
          "sha256": "fc8bcd31e972f553c5b85985e858d60867228f17ebc207bff1ac00e02a9cf635",
          "sha1": "ca1432b819c3d39c2122227de8a3c4f58359dc83",
          "md5": "f5269ec7bd008273f721eba996716170"
        }
      ]
    }
  ]
}
