{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.5.0-SNAPSHOT/kotlinx-serialization-protobuf-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jvm-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-protobuf-jvm-1.5.0-SNAPSHOT.jar",
          "size": 100737,
          "sha512": "b737aa73aeb0c0357401c047706e972f3e827290ba6af802ce6128c38366e125fda45e32cf38db086e0b8086e606321bb7968d71b6e51536e9cc8e8ea1c0428d",
          "sha256": "5baef6aa8306413fcdd987d2bd1ae73fdfa83734673938e4be1e3079a6670f1b",
          "sha1": "452e75c702f06d6fec00176e78bb50f9053ced3b",
          "md5": "97c445b10c4b6a7644814f95b48a5c0b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jvm-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-protobuf-jvm-1.5.0-SNAPSHOT.jar",
          "size": 100737,
          "sha512": "b737aa73aeb0c0357401c047706e972f3e827290ba6af802ce6128c38366e125fda45e32cf38db086e0b8086e606321bb7968d71b6e51536e9cc8e8ea1c0428d",
          "sha256": "5baef6aa8306413fcdd987d2bd1ae73fdfa83734673938e4be1e3079a6670f1b",
          "sha1": "452e75c702f06d6fec00176e78bb50f9053ced3b",
          "md5": "97c445b10c4b6a7644814f95b48a5c0b"
        }
      ]
    }
  ]
}
