{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.jar",
          "size": 8946,
          "sha512": "a1488203fd47c469203e4f383efc1416e4ce5604b748914fc2b936312c8610a562404fe68c614072ff9038ae26eeec47676ff27714b2498e4a624e21e0d1dd56",
          "sha256": "bfd7f0d67637c4617a591d13bdba5c6aefe865ae597dc578c6df6f93dc0012f6",
          "sha1": "faa76432106e1184b3c44d3b735ea60ca53e1f64",
          "md5": "fb88afb5ef77e8f185afbf8d6334299d"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.jar",
          "size": 8946,
          "sha512": "a1488203fd47c469203e4f383efc1416e4ce5604b748914fc2b936312c8610a562404fe68c614072ff9038ae26eeec47676ff27714b2498e4a624e21e0d1dd56",
          "sha256": "bfd7f0d67637c4617a591d13bdba5c6aefe865ae597dc578c6df6f93dc0012f6",
          "sha1": "faa76432106e1184b3c44d3b735ea60ca53e1f64",
          "md5": "fb88afb5ef77e8f185afbf8d6334299d"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.klib",
          "size": 12269,
          "sha512": "40b2f7a72f34ff907972cbb837e6519ef84a7323adde39654d3a3daf79fbee626b079853fadae2a55f41f85189a021c5d88d78744f5ce9d01261658e2d99520c",
          "sha256": "f1e501a7fd6ab11f414b32924259b2d87bcefc54b6fe89acce15a8789070d661",
          "sha1": "28eebddcb725aac68715e642f28e8a332ad5ec60",
          "md5": "54076066e12b5d6e7647eca9ae5bc30a"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.klib",
          "size": 12269,
          "sha512": "40b2f7a72f34ff907972cbb837e6519ef84a7323adde39654d3a3daf79fbee626b079853fadae2a55f41f85189a021c5d88d78744f5ce9d01261658e2d99520c",
          "sha256": "f1e501a7fd6ab11f414b32924259b2d87bcefc54b6fe89acce15a8789070d661",
          "sha1": "28eebddcb725aac68715e642f28e8a332ad5ec60",
          "md5": "54076066e12b5d6e7647eca9ae5bc30a"
        }
      ]
    }
  ]
}
