{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.jar",
          "size": 8944,
          "sha512": "e656916eead1e648a472171338d9eb35b183946633bd454b627db3ac4c12611a357e9d8e8f47f6ccbc001ad638ce96e61a63a4e0c96314444f0becef3ac822b9",
          "sha256": "5396ac3ab33464f603e4f76b13ec5b965b48c6abd113ab92380103e180f9f7ea",
          "sha1": "816d9c16e890e04e120fdbab09822d00b60d53ef",
          "md5": "8c385a9dfe415ee32d8e4174e3517870"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.jar",
          "size": 8944,
          "sha512": "e656916eead1e648a472171338d9eb35b183946633bd454b627db3ac4c12611a357e9d8e8f47f6ccbc001ad638ce96e61a63a4e0c96314444f0becef3ac822b9",
          "sha256": "5396ac3ab33464f603e4f76b13ec5b965b48c6abd113ab92380103e180f9f7ea",
          "sha1": "816d9c16e890e04e120fdbab09822d00b60d53ef",
          "md5": "8c385a9dfe415ee32d8e4174e3517870"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.klib",
          "size": 12274,
          "sha512": "da91b35ad50ddd5bafe38d43e3e68783d4a9492a9cdfbfefbd0d1ee0aa47383b7e8c59c49f901a17b2be8e2592e1682f3b82d10faa5ee87ef023e04ee48829d0",
          "sha256": "b694c6e614309a0f695c9de29ac86afd1e75876112740d82af0620825a4b69c2",
          "sha1": "627ed78288f5629e9091b2f61df5cab334f1e4ae",
          "md5": "570ac3f8b0e092855ac438686fd47b06"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.klib",
          "size": 12274,
          "sha512": "da91b35ad50ddd5bafe38d43e3e68783d4a9492a9cdfbfefbd0d1ee0aa47383b7e8c59c49f901a17b2be8e2592e1682f3b82d10faa5ee87ef023e04ee48829d0",
          "sha256": "b694c6e614309a0f695c9de29ac86afd1e75876112740d82af0620825a4b69c2",
          "sha1": "627ed78288f5629e9091b2f61df5cab334f1e4ae",
          "md5": "570ac3f8b0e092855ac438686fd47b06"
        }
      ]
    }
  ]
}
