{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-metadata-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-okio-1.5.0-SNAPSHOT.jar",
          "size": 5672,
          "sha512": "12a6033deb7610898479ea550459a29a78383f7767522f5ab9a44ac3864d1a39f538c062e9afce4ac07e5c2c4f4be6869b5361b4c51c5e4e76ea136f4196c8a7",
          "sha256": "408e178ee5b2aa54204ce61dbb2b9a9290c8125881938920e55b4ebc575d015a",
          "sha1": "13c7b6c1a92c10676eb4f3676943646d9dc36644",
          "md5": "c5d1398269076f61ec944a8f0f1f65f3"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-okio-js/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-okio-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-okio-js/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-okio-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-okio-js/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-okio-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-okio-js/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-okio-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-okio-jvm/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-jvm-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-okio-jvm",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-okio-jvm/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-jvm-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-okio-jvm",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-okio-native/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-native-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-okio-native",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
