{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.5.0-SNAPSHOT/kotlinx-serialization-cbor-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-cbor-js-1.5.0-SNAPSHOT.jar",
          "size": 56319,
          "sha512": "b9468bd7f5c337993321535e6b594bbe553ccc2464b6688b39d7f8b25e2f174a89c5ccb81b0f63a99cb90a0061c93f8617e679935ed1221ca3e2ba3930a370ca",
          "sha256": "665a4060c4efb6edfe368ac8689f4c951f7b292247ac7488a7276e40e3f2459c",
          "sha1": "cadb299f089f408546c407ae8f76ffcad78e40e1",
          "md5": "624fa1c0bdb172a44500e58a95ced1fb"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-cbor-js-1.5.0-SNAPSHOT.jar",
          "size": 56319,
          "sha512": "b9468bd7f5c337993321535e6b594bbe553ccc2464b6688b39d7f8b25e2f174a89c5ccb81b0f63a99cb90a0061c93f8617e679935ed1221ca3e2ba3930a370ca",
          "sha256": "665a4060c4efb6edfe368ac8689f4c951f7b292247ac7488a7276e40e3f2459c",
          "sha1": "cadb299f089f408546c407ae8f76ffcad78e40e1",
          "md5": "624fa1c0bdb172a44500e58a95ced1fb"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-cbor-js-1.5.0-SNAPSHOT.klib",
          "size": 51932,
          "sha512": "e9792a23e6c3c87ecda46bbf2e470ed273b6959574d1bac2e11c68988648e0e02ce73009b299868c9f5d23e1187ffe1a9489c40b1d8689a1d45af1c3fd8b98be",
          "sha256": "175b90a44979b5fb308a0253c66fd9eeb511ee6200ee78f0ee8ae57b7390035e",
          "sha1": "600dea3f878cda13f44916ac837a896a6ce750cd",
          "md5": "2eadbc6ff9f679cf01b48a0f737c2745"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-cbor-js-1.5.0-SNAPSHOT.klib",
          "size": 51932,
          "sha512": "e9792a23e6c3c87ecda46bbf2e470ed273b6959574d1bac2e11c68988648e0e02ce73009b299868c9f5d23e1187ffe1a9489c40b1d8689a1d45af1c3fd8b98be",
          "sha256": "175b90a44979b5fb308a0253c66fd9eeb511ee6200ee78f0ee8ae57b7390035e",
          "sha1": "600dea3f878cda13f44916ac837a896a6ce750cd",
          "md5": "2eadbc6ff9f679cf01b48a0f737c2745"
        }
      ]
    }
  ]
}
