{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.5.0-SNAPSHOT/kotlinx-serialization-core-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-native-1.5.0-SNAPSHOT.klib",
          "size": 275179,
          "sha512": "8df4cad8827df0270ae00525367d74cb9c1b10b7888b19a628a11ed6275d67efbb4fb2deeafd67f166fce88130749903a7c3a1b38985b896d1aa1b1271ce8fe4",
          "sha256": "0750282d41e3056965162feedbbfdd31d607e051c807b21caf82dca9c807b0a5",
          "sha1": "7d31f8fe37399e346382aad467ecc9d9d50b33e6",
          "md5": "37144faf72b083a5f3a461d643576e40"
        }
      ]
    }
  ]
}
