{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.5.0-SNAPSHOT/kotlinx-serialization-protobuf-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-protobuf-js-1.5.0-SNAPSHOT.jar",
          "size": 126793,
          "sha512": "32334ba997cbba84125a3310c5823cd7e3b5c5ac6b2c08dda8e8cdefeb8ad9b5321d4fe36d65856c36dcca3929db6b69465ff8e6d01e2be725dc1dd4729dfa00",
          "sha256": "1e18b993c48768e1546c1c3f19be4a513a6a03f963d6193bffb3bf7948d36565",
          "sha1": "62a6ef891b6b59730c67faa46f323ef731ee7837",
          "md5": "32bc505d1d4de55dc70622f09de992da"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-protobuf-js-1.5.0-SNAPSHOT.jar",
          "size": 126793,
          "sha512": "32334ba997cbba84125a3310c5823cd7e3b5c5ac6b2c08dda8e8cdefeb8ad9b5321d4fe36d65856c36dcca3929db6b69465ff8e6d01e2be725dc1dd4729dfa00",
          "sha256": "1e18b993c48768e1546c1c3f19be4a513a6a03f963d6193bffb3bf7948d36565",
          "sha1": "62a6ef891b6b59730c67faa46f323ef731ee7837",
          "md5": "32bc505d1d4de55dc70622f09de992da"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-js-1.5.0-SNAPSHOT.klib",
          "size": 122177,
          "sha512": "a94da3ca4012b9e6514223c8b52c131a6157ab513b8cc702cfc5ff7a52ae8a77d2de52ce4318cd8cd96544fedbb096f59c55e4a972b5d59e45d95db03ecd1183",
          "sha256": "c35dd7c52bcc933ff7a551849c2c0880d4fefe9564aaa00389f8563f400378f7",
          "sha1": "7a73040fa699029856fe3c8773f0b5ca68f76e42",
          "md5": "f647c18a807a51b3e6e077b363a37d48"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-js-1.5.0-SNAPSHOT.klib",
          "size": 122177,
          "sha512": "a94da3ca4012b9e6514223c8b52c131a6157ab513b8cc702cfc5ff7a52ae8a77d2de52ce4318cd8cd96544fedbb096f59c55e4a972b5d59e45d95db03ecd1183",
          "sha256": "c35dd7c52bcc933ff7a551849c2c0880d4fefe9564aaa00389f8563f400378f7",
          "sha1": "7a73040fa699029856fe3c8773f0b5ca68f76e42",
          "md5": "f647c18a807a51b3e6e077b363a37d48"
        }
      ]
    }
  ]
}
