{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-metadata-1.5.0-SNAPSHOT-all.jar",
          "url": "kotlinx-serialization-properties-1.5.0-SNAPSHOT-all.jar",
          "size": 5215,
          "sha512": "cc78e7d8ede392e54f44dbcb4ce2eec1c346a6bae15ee47044cb3c679c85f0834302f0fe3cf26a2dbade7cdc3999cf5ac15aa98007088c50b9bf54b7ffc6fbd3",
          "sha256": "0e9d64f94b83006b2ede047d21b71a0eb5ba9d17792adcc6fd0b81fd7f6d4c19",
          "sha1": "d148560c53b56b62c1aaa8f8657c1ee846a18938",
          "md5": "308e9a29e870b66e7e23787f996ffe55"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-properties-1.5.0-SNAPSHOT.jar",
          "size": 3197,
          "sha512": "fcc6e6ca22cfb78b0fd7b5d656bfb1b94b73bb108dd8ae6b8ab0574021122bb4b07c973cfdbb3c8515c609ee50fcdc9ce5d8eaa0f01ef2680f62ae4a16b2aba9",
          "sha256": "c129c93758df271ca217d59f226bacf6387e1f7b2fca124527adfd82679d4c74",
          "sha1": "5cae972f8d8c995aea97647da2321f528329a490",
          "md5": "7bfae608f26d837e1fe53a8d2b510d86"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-properties-js/1.5.0-SNAPSHOT/kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-properties-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-properties-js/1.5.0-SNAPSHOT/kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-properties-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-properties-js/1.5.0-SNAPSHOT/kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-properties-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-properties-js/1.5.0-SNAPSHOT/kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-properties-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-properties-jvm/1.5.0-SNAPSHOT/kotlinx-serialization-properties-jvm-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-properties-jvm",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-properties-jvm/1.5.0-SNAPSHOT/kotlinx-serialization-properties-jvm-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-properties-jvm",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-properties-native/1.5.0-SNAPSHOT/kotlinx-serialization-properties-native-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-properties-native",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
