{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.5.0-SNAPSHOT/kotlinx-serialization-cbor-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.5.0-SNAPSHOT.jar",
          "size": 34373,
          "sha512": "f83c805b6825ad8c4074d728301c79f2e2cdbd9de3ba44741f6351e64f18692f7ed86be3a573b0cc1e29d5d80a40404a02ab4aef80d370e0f89d1fd8cd051046",
          "sha256": "a3f4814d7d6ae28363fb0b93e720f8c52e3bba2d2037ee0375a4fee4e331008c",
          "sha1": "4cff81f4a64c60928beb894cf7d301be3bc2913e",
          "md5": "6116d1ffa242d1a5199c0a24b830ef46"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.5.0-SNAPSHOT.jar",
          "size": 34373,
          "sha512": "f83c805b6825ad8c4074d728301c79f2e2cdbd9de3ba44741f6351e64f18692f7ed86be3a573b0cc1e29d5d80a40404a02ab4aef80d370e0f89d1fd8cd051046",
          "sha256": "a3f4814d7d6ae28363fb0b93e720f8c52e3bba2d2037ee0375a4fee4e331008c",
          "sha1": "4cff81f4a64c60928beb894cf7d301be3bc2913e",
          "md5": "6116d1ffa242d1a5199c0a24b830ef46"
        }
      ]
    }
  ]
}
