{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.5.0-SNAPSHOT/kotlinx-serialization-json-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-native-1.5.0-SNAPSHOT.klib",
          "size": 226939,
          "sha512": "aea31b2c84bd0d23b0c6430304806e17ac069d08da5a16053beead45bf8f50d5c25bd7cbe70c071d886c5b217788a2f645f790835714f1b7f7c3086e4d65e06f",
          "sha256": "15bf1edf815a67bcfe84d6d3635cd38b55bce59a26dd8989045c91c6d00329d6",
          "sha1": "bd30a84eef0cc6621b86336bf6b824a0236aa985",
          "md5": "f3f6ca71c402d87a2a001aac9af1d783"
        }
      ]
    }
  ]
}
