{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.5.0-SNAPSHOT/kotlinx-serialization-properties-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-native-1.5.0-SNAPSHOT.klib",
          "size": 19442,
          "sha512": "3098daf4056122f83aa062386d18018217f6e342e2d0ba7d4e2ef2f0dc150d17e29f2286a4290e466beba9cdc9138ea6b8e0ccdfc5ac72faebf38a700f5b50c8",
          "sha256": "74a24c5a0c1c024620d059d59c6fbf38bd939da63b50cc8abbe60571b1405057",
          "sha1": "ffcc27c4d07afd2583d69d118a046e365b271159",
          "md5": "c9c4f6bdec1cb8783f71dac382e5ad9a"
        }
      ]
    }
  ]
}
