{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.5.0-SNAPSHOT/kotlinx-serialization-properties-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-native-1.5.0-SNAPSHOT.klib",
          "size": 19442,
          "sha512": "bbdc96ed70026d22c91b50e141340cc9dfbd73ad13d6630e9e159ee72f6c510b2d6dbd6bd6ea695dbcb589f88363783119f97b4224fa66bd646b9662b8ca4413",
          "sha256": "694a71912ea55878d4563741bab3f95a6fcf7aa077d5b4550343b99430442229",
          "sha1": "0c3b2f8659043052b1fe4b65011f3f9a08fb3877",
          "md5": "e961e4b25dba7b5582daefdc041b3159"
        }
      ]
    }
  ]
}
