{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.5.0-SNAPSHOT/kotlinx-serialization-protobuf-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf.klib",
          "url": "kotlinx-serialization-protobuf-native-1.5.0-SNAPSHOT.klib",
          "size": 119322,
          "sha512": "cad5614a91866bd1cbf97455973d1496ddcc839d5cfeecca1c403513744b28a3cd59c7f36891bd27473601af76a073055cf36f6cdff2b565a7d55718a227ed3b",
          "sha256": "0798945d1377cce93f61a1ad790df40fd0d6f4b2cd31ca94f5b7a4bbe4619b2a",
          "sha1": "c90521b6b4e52ea49d4d7521f5e8019c7821cc06",
          "md5": "ad99234a3e2d494ff63a8442f490a173"
        }
      ]
    }
  ]
}
