{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.5.0-SNAPSHOT/kotlinx-serialization-properties-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.jar",
          "size": 30038,
          "sha512": "cd4e209b989747a7bca22553be780476b5181d5ed7e77d96b6a70cdcf29ff4789d6c4e7efb0b5a39a919de2a0cf15d7e46db52bf88a9b756f82fcb19356e4370",
          "sha256": "7b40862fce17ed27c30a0deb1b9b383e9d9f7d6be55ae68493aced3699e9444d",
          "sha1": "43c6cb2306d655dc973af5318edcec9b2b44b0f3",
          "md5": "0561cc8e96c053b62bd1f077bd6f2ee1"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.jar",
          "size": 30038,
          "sha512": "cd4e209b989747a7bca22553be780476b5181d5ed7e77d96b6a70cdcf29ff4789d6c4e7efb0b5a39a919de2a0cf15d7e46db52bf88a9b756f82fcb19356e4370",
          "sha256": "7b40862fce17ed27c30a0deb1b9b383e9d9f7d6be55ae68493aced3699e9444d",
          "sha1": "43c6cb2306d655dc973af5318edcec9b2b44b0f3",
          "md5": "0561cc8e96c053b62bd1f077bd6f2ee1"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.klib",
          "size": 16526,
          "sha512": "84a6903a183791b90cc88b5d9f4f154008901fa157cb7f754a8e9e25f77ceca84d2c7cfaa10c688ba02e981d699d7aaeccefbd3eeeec8bcc01f2cd2223980865",
          "sha256": "178cda230457ce66f7c50497154358482058272e0babbe6b2ea899642a6f1757",
          "sha1": "a412cc1b15c81377365d1b09eb24f65b10b00159",
          "md5": "b3e0cc68b5c9f5aeba59e729cfa46b56"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.klib",
          "size": 16526,
          "sha512": "84a6903a183791b90cc88b5d9f4f154008901fa157cb7f754a8e9e25f77ceca84d2c7cfaa10c688ba02e981d699d7aaeccefbd3eeeec8bcc01f2cd2223980865",
          "sha256": "178cda230457ce66f7c50497154358482058272e0babbe6b2ea899642a6f1757",
          "sha1": "a412cc1b15c81377365d1b09eb24f65b10b00159",
          "md5": "b3e0cc68b5c9f5aeba59e729cfa46b56"
        }
      ]
    }
  ]
}
