{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.5.0-SNAPSHOT/kotlinx-serialization-properties-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.jar",
          "size": 30038,
          "sha512": "cd4e209b989747a7bca22553be780476b5181d5ed7e77d96b6a70cdcf29ff4789d6c4e7efb0b5a39a919de2a0cf15d7e46db52bf88a9b756f82fcb19356e4370",
          "sha256": "7b40862fce17ed27c30a0deb1b9b383e9d9f7d6be55ae68493aced3699e9444d",
          "sha1": "43c6cb2306d655dc973af5318edcec9b2b44b0f3",
          "md5": "0561cc8e96c053b62bd1f077bd6f2ee1"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.jar",
          "size": 30038,
          "sha512": "cd4e209b989747a7bca22553be780476b5181d5ed7e77d96b6a70cdcf29ff4789d6c4e7efb0b5a39a919de2a0cf15d7e46db52bf88a9b756f82fcb19356e4370",
          "sha256": "7b40862fce17ed27c30a0deb1b9b383e9d9f7d6be55ae68493aced3699e9444d",
          "sha1": "43c6cb2306d655dc973af5318edcec9b2b44b0f3",
          "md5": "0561cc8e96c053b62bd1f077bd6f2ee1"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.klib",
          "size": 16526,
          "sha512": "c9e2d89daadbbf00ea6c2fa3e13622c59bd7bc340679b49002d2feade5dd701aa2a7690fc97095cef47f107d14071ac76bbd8c440995a0ee1253869e5f7ff981",
          "sha256": "b11381095e67297b5aa29b0a15bedad837fe152f98ccecbcd2985242af5fe97e",
          "sha1": "6b5cf49c6d033bcbd84e3dbb2cfd54eddfb0e3ec",
          "md5": "f60b2c14a33e8171e46da49997800c14"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-properties-js-1.5.0-SNAPSHOT.klib",
          "size": 16526,
          "sha512": "c9e2d89daadbbf00ea6c2fa3e13622c59bd7bc340679b49002d2feade5dd701aa2a7690fc97095cef47f107d14071ac76bbd8c440995a0ee1253869e5f7ff981",
          "sha256": "b11381095e67297b5aa29b0a15bedad837fe152f98ccecbcd2985242af5fe97e",
          "sha1": "6b5cf49c6d033bcbd84e3dbb2cfd54eddfb0e3ec",
          "md5": "f60b2c14a33e8171e46da49997800c14"
        }
      ]
    }
  ]
}
