{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-hocon",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "size": 53105,
          "sha512": "7d895e2023b2cd855337383b246c7a3e5ccf4267b52b9091dea0646763e3c171de2c9097cc491ba02976a221a4a2f1edc4fc67e86eae22ce93259f7db970f28d",
          "sha256": "82bb13104eb0f33520372d48d6d987e91d4d1b029208924ca82efdcb382d288b",
          "sha1": "2fc11ce9153a4fc7f2a74214fd4d8edd6cc543d4",
          "md5": "da720b99d3d5326773bda548a5caba3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "size": 53105,
          "sha512": "7d895e2023b2cd855337383b246c7a3e5ccf4267b52b9091dea0646763e3c171de2c9097cc491ba02976a221a4a2f1edc4fc67e86eae22ce93259f7db970f28d",
          "sha256": "82bb13104eb0f33520372d48d6d987e91d4d1b029208924ca82efdcb382d288b",
          "sha1": "2fc11ce9153a4fc7f2a74214fd4d8edd6cc543d4",
          "md5": "da720b99d3d5326773bda548a5caba3a"
        }
      ]
    }
  ]
}
