{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-hocon",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "size": 53105,
          "sha512": "012dd57d1d7dc8c36d3ed4c4d32b077913bf5464a390133306b7febaa285ad157886b56540ef9bbf0342db74db731941155d8dbefbdc888ec5f117cd5d21a93d",
          "sha256": "2cd8332d4b117405b17efebe00d0a6766f12c7cca94c748dd42043ecbb52772a",
          "sha1": "f2faced531f6e99067956fde5c3c27adc5654935",
          "md5": "5614bcf96b09ed55e8094e6b425526e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "size": 53105,
          "sha512": "012dd57d1d7dc8c36d3ed4c4d32b077913bf5464a390133306b7febaa285ad157886b56540ef9bbf0342db74db731941155d8dbefbdc888ec5f117cd5d21a93d",
          "sha256": "2cd8332d4b117405b17efebe00d0a6766f12c7cca94c748dd42043ecbb52772a",
          "sha1": "f2faced531f6e99067956fde5c3c27adc5654935",
          "md5": "5614bcf96b09ed55e8094e6b425526e5"
        }
      ]
    }
  ]
}
