{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.5.0-SNAPSHOT/kotlinx-serialization-json-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-jvm-1.5.0-SNAPSHOT.jar",
          "size": 234704,
          "sha512": "fc0b994877b2be3a8da2bd39c0c779ba7da1fb6d6e73cb146f1b752c183832089346ad512a68675ca511a3be4cfd62d888a403d203581fcee326c56bc14cbc93",
          "sha256": "3916fb6a742958d74a67e928a202320f2a03ab9cc206373f1a578f1d14997eb7",
          "sha1": "76f3282d549c0ea50623bf0114f2891247a77b23",
          "md5": "a71c576030f643e23c74feb90171dabe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-jvm-1.5.0-SNAPSHOT.jar",
          "size": 234704,
          "sha512": "fc0b994877b2be3a8da2bd39c0c779ba7da1fb6d6e73cb146f1b752c183832089346ad512a68675ca511a3be4cfd62d888a403d203581fcee326c56bc14cbc93",
          "sha256": "3916fb6a742958d74a67e928a202320f2a03ab9cc206373f1a578f1d14997eb7",
          "sha1": "76f3282d549c0ea50623bf0114f2891247a77b23",
          "md5": "a71c576030f643e23c74feb90171dabe"
        }
      ]
    }
  ]
}
