{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.5.0-SNAPSHOT/kotlinx-serialization-json-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-js-1.5.0-SNAPSHOT.jar",
          "size": 206334,
          "sha512": "5c320ad6406c53acb0474cfe91b292dca8ddc13877432f1c31d219937daa226590539b428e986bbf7d91a32ade187dca841ffc59186f82e9e74a9ef03fcbd96a",
          "sha256": "f219b7731bf8cb2cf3098c818a164de6b678c5fd936d10e5fd5458d507773134",
          "sha1": "149a4cfdf7d73ccd2d2184c707a3d6c0832b8080",
          "md5": "ff546ca23814ed809f59c0827f1abb5a"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-js-1.5.0-SNAPSHOT.jar",
          "size": 206334,
          "sha512": "5c320ad6406c53acb0474cfe91b292dca8ddc13877432f1c31d219937daa226590539b428e986bbf7d91a32ade187dca841ffc59186f82e9e74a9ef03fcbd96a",
          "sha256": "f219b7731bf8cb2cf3098c818a164de6b678c5fd936d10e5fd5458d507773134",
          "sha1": "149a4cfdf7d73ccd2d2184c707a3d6c0832b8080",
          "md5": "ff546ca23814ed809f59c0827f1abb5a"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-js-1.5.0-SNAPSHOT.klib",
          "size": 271156,
          "sha512": "5f8fc250dcf13b9cce6658a8edcc88e4b1abb15db771c1fcec61a8867615f1ebbb0dfbe888c3fc62d2e609df310243e3b7115b069214d136d0493454f809d3f8",
          "sha256": "fd5491c684523fd54e7f4db4e46b5d5a128e652696642fc22e531b1f2c3738d6",
          "sha1": "9da47bc7532965bd9e07654bda3ae2021cc0ec59",
          "md5": "b590dfff019c778fb68512e7c879244b"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-js-1.5.0-SNAPSHOT.klib",
          "size": 271156,
          "sha512": "5f8fc250dcf13b9cce6658a8edcc88e4b1abb15db771c1fcec61a8867615f1ebbb0dfbe888c3fc62d2e609df310243e3b7115b069214d136d0493454f809d3f8",
          "sha256": "fd5491c684523fd54e7f4db4e46b5d5a128e652696642fc22e531b1f2c3738d6",
          "sha1": "9da47bc7532965bd9e07654bda3ae2021cc0ec59",
          "md5": "b590dfff019c778fb68512e7c879244b"
        }
      ]
    }
  ]
}
