{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.5.0-SNAPSHOT/kotlinx-serialization-json-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-js-1.5.0-SNAPSHOT.jar",
          "size": 206334,
          "sha512": "5c320ad6406c53acb0474cfe91b292dca8ddc13877432f1c31d219937daa226590539b428e986bbf7d91a32ade187dca841ffc59186f82e9e74a9ef03fcbd96a",
          "sha256": "f219b7731bf8cb2cf3098c818a164de6b678c5fd936d10e5fd5458d507773134",
          "sha1": "149a4cfdf7d73ccd2d2184c707a3d6c0832b8080",
          "md5": "ff546ca23814ed809f59c0827f1abb5a"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-js-1.5.0-SNAPSHOT.jar",
          "size": 206334,
          "sha512": "5c320ad6406c53acb0474cfe91b292dca8ddc13877432f1c31d219937daa226590539b428e986bbf7d91a32ade187dca841ffc59186f82e9e74a9ef03fcbd96a",
          "sha256": "f219b7731bf8cb2cf3098c818a164de6b678c5fd936d10e5fd5458d507773134",
          "sha1": "149a4cfdf7d73ccd2d2184c707a3d6c0832b8080",
          "md5": "ff546ca23814ed809f59c0827f1abb5a"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-js-1.5.0-SNAPSHOT.klib",
          "size": 271154,
          "sha512": "fbb7d665f223e5a2f26e8eb8fb4ca41a49d8f6bc183fad609c0b0d330baa741c7027154d452bd7e16eb280ca00561dd22b1ea7a88bb537fec98493e848ddde99",
          "sha256": "40ef170e15a6fe380836ebe9b63f746a45a1d0f6fa2c75c992be364877fcaa94",
          "sha1": "2e5cea7600aa6067ff6f492342215ca8c3f8b220",
          "md5": "9e6cf9a9d6307d4dac5c2a5977ef8b5c"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-js-1.5.0-SNAPSHOT.klib",
          "size": 271154,
          "sha512": "fbb7d665f223e5a2f26e8eb8fb4ca41a49d8f6bc183fad609c0b0d330baa741c7027154d452bd7e16eb280ca00561dd22b1ea7a88bb537fec98493e848ddde99",
          "sha256": "40ef170e15a6fe380836ebe9b63f746a45a1d0f6fa2c75c992be364877fcaa94",
          "sha1": "2e5cea7600aa6067ff6f492342215ca8c3f8b220",
          "md5": "9e6cf9a9d6307d4dac5c2a5977ef8b5c"
        }
      ]
    }
  ]
}
