{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jvm-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-okio-jvm-1.5.0-SNAPSHOT.jar",
          "size": 7463,
          "sha512": "c81d4d6f303869ecf2d25f7bb600bd4efd7f44dc8cb5bd22a575769635ed694b07b8daecd19ae8ece7689c86976adff2d5ccd0d79a7c7c03df05350fd635602e",
          "sha256": "375c04a1429b337cc08724febb522fed251041380fa253f865774e3374742698",
          "sha1": "c08b82b8b9e8c86eb18683da2892a4d0661de8df",
          "md5": "671ed976299473c21110a1fa3809cab9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-jvm-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-okio-jvm-1.5.0-SNAPSHOT.jar",
          "size": 7463,
          "sha512": "c81d4d6f303869ecf2d25f7bb600bd4efd7f44dc8cb5bd22a575769635ed694b07b8daecd19ae8ece7689c86976adff2d5ccd0d79a7c7c03df05350fd635602e",
          "sha256": "375c04a1429b337cc08724febb522fed251041380fa253f865774e3374742698",
          "sha1": "c08b82b8b9e8c86eb18683da2892a4d0661de8df",
          "md5": "671ed976299473c21110a1fa3809cab9"
        }
      ]
    }
  ]
}
