{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.5.0-SNAPSHOT/kotlinx-serialization-core-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-core-js-1.5.0-SNAPSHOT.jar",
          "size": 224946,
          "sha512": "dfadbe808a82e42128c9de0b1a2c67ef8e4e009867a91856cd3be815ad29edc49a3c5da5205cdc223ac2014c12df5042a6ee4ae4113c1155fdd58cc235979c39",
          "sha256": "f1fffe105ab0bc85c90d61b5b295ef2caa18102f5a5221dacdbf1cae954a351c",
          "sha1": "e4e21c9ec3c91c87e83f2528c931b5a61ec1ae42",
          "md5": "a070a6218b26b1877bf523a62d3317bb"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-core-js-1.5.0-SNAPSHOT.jar",
          "size": 224946,
          "sha512": "dfadbe808a82e42128c9de0b1a2c67ef8e4e009867a91856cd3be815ad29edc49a3c5da5205cdc223ac2014c12df5042a6ee4ae4113c1155fdd58cc235979c39",
          "sha256": "f1fffe105ab0bc85c90d61b5b295ef2caa18102f5a5221dacdbf1cae954a351c",
          "sha1": "e4e21c9ec3c91c87e83f2528c931b5a61ec1ae42",
          "md5": "a070a6218b26b1877bf523a62d3317bb"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-core-js-1.5.0-SNAPSHOT.klib",
          "size": 290713,
          "sha512": "6c34c4fa4f0a0ee1867db1de5c4b75fbe4eeab35dabfe3fd554c30f5f7a016fbff5ad69c914851a54f7217b2e24ed7eba395cc225184cde0d3e671c59434196b",
          "sha256": "4c0524e041d7db21529aedbae99d823c177db2af935a3909184cbe95e85c0d30",
          "sha1": "625d07a09c9ab5b29c2761a8f3d9f9ba15669372",
          "md5": "f09ceb4c9aec6d2d9052571899a65117"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-core-js-1.5.0-SNAPSHOT.klib",
          "size": 290713,
          "sha512": "6c34c4fa4f0a0ee1867db1de5c4b75fbe4eeab35dabfe3fd554c30f5f7a016fbff5ad69c914851a54f7217b2e24ed7eba395cc225184cde0d3e671c59434196b",
          "sha256": "4c0524e041d7db21529aedbae99d823c177db2af935a3909184cbe95e85c0d30",
          "sha1": "625d07a09c9ab5b29c2761a8f3d9f9ba15669372",
          "md5": "f09ceb4c9aec6d2d9052571899a65117"
        }
      ]
    }
  ]
}
