{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.5.0-SNAPSHOT/kotlinx-serialization-json-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-native-1.5.0-SNAPSHOT.klib",
          "size": 228307,
          "sha512": "84e579748517f5fdee8e0f40329d192cbb32f702dca05a8381463105bc6f2beb8277ee296ad2b505cfd615a720491072bb71e50276b51198e7052dc95c1f81ea",
          "sha256": "dd737ae68a6cf65f86809855c4337a7b68a1ec17c92e0569d7ba824e7bc54a5f",
          "sha1": "725597f91a82ba32cd17fbb8008cf5f7f17fea25",
          "md5": "4b55ae840d29f57035ea57391ab33637"
        }
      ]
    }
  ]
}
