{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.5.0-SNAPSHOT/kotlinx-serialization-json-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-native-1.5.0-SNAPSHOT.klib",
          "size": 226936,
          "sha512": "d9bd7bf14a22210da29627bb16d0227dcbc26ecab756a917d6f1e10ba26fd740618b87eb4e4829524c25fe275bdf74146b743d9721cafb7488344a732a5b6dcf",
          "sha256": "9fe6858f55edb37fec77a6bf3c14515cc945721b88be31b88aef5b71f52f57fc",
          "sha1": "a7476fbe6a00558a07cf93c3b58964c5cf2e3a3f",
          "md5": "0c1d09fbb80ccb2022a47de3dd1ca4d8"
        }
      ]
    }
  ]
}
