{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.5.0-SNAPSHOT/kotlinx-serialization-protobuf-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-protobuf-js-1.5.0-SNAPSHOT.jar",
          "size": 126737,
          "sha512": "cd89394eaa1159ed2b5e8bf6fff157f5445b8adec2a61c140da8761c9865f393ab3d3d6250b2d1412cad18c7af52dab516624aa8e247d9ff7f6cbd8af9ca6bda",
          "sha256": "5acfa42308f87b26500e50ac43f215b46b2ed1a9b57fefd7d4482b38ff6335d5",
          "sha1": "42f273c94789d26d934e1697649e831e089523ca",
          "md5": "f4d11a90211fc4b6c050046e9256ff6d"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jslegacy-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-protobuf-js-1.5.0-SNAPSHOT.jar",
          "size": 126737,
          "sha512": "cd89394eaa1159ed2b5e8bf6fff157f5445b8adec2a61c140da8761c9865f393ab3d3d6250b2d1412cad18c7af52dab516624aa8e247d9ff7f6cbd8af9ca6bda",
          "sha256": "5acfa42308f87b26500e50ac43f215b46b2ed1a9b57fefd7d4482b38ff6335d5",
          "sha1": "42f273c94789d26d934e1697649e831e089523ca",
          "md5": "f4d11a90211fc4b6c050046e9256ff6d"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-js-1.5.0-SNAPSHOT.klib",
          "size": 122167,
          "sha512": "1857017257019691081f5027d7701cb46b2ad90f33895997a60f983b227e347204fa79654a6dd90a8feb9af56b083c11534adb37d904970e7cb14966ca3e2b8c",
          "sha256": "0eb065157958eeb8ed6709631088d78564586aeff36ba4c52d5ef25fff5c6f72",
          "sha1": "a7a7e4146cef68020ccf4b8ac44a1b8044012f5d",
          "md5": "19e5b525cf6be45bedbee39eb3c7528d"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jsir-1.5.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-js-1.5.0-SNAPSHOT.klib",
          "size": 122167,
          "sha512": "1857017257019691081f5027d7701cb46b2ad90f33895997a60f983b227e347204fa79654a6dd90a8feb9af56b083c11534adb37d904970e7cb14966ca3e2b8c",
          "sha256": "0eb065157958eeb8ed6709631088d78564586aeff36ba4c52d5ef25fff5c6f72",
          "sha1": "a7a7e4146cef68020ccf4b8ac44a1b8044012f5d",
          "md5": "19e5b525cf6be45bedbee39eb3c7528d"
        }
      ]
    }
  ]
}
