{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-hocon",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "size": 53105,
          "sha512": "23b4a77c2768be8cc02be3cd6dd21eba924069733cf0d4c5b44a78e91484151ef2fb0bf55eb218962db011b6a03cbd9c33a21aaba747b9f6346174c233aba8cd",
          "sha256": "a9274ee3a6c891c71af14d19f695a1a93c5bb4aa2bb80d20465711361f8ac546",
          "sha1": "27dceae977fe59ce0859020bc3dec68aa30cd064",
          "md5": "04c164a6c3c30d9460d11ad8b4c86ab4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "size": 53105,
          "sha512": "23b4a77c2768be8cc02be3cd6dd21eba924069733cf0d4c5b44a78e91484151ef2fb0bf55eb218962db011b6a03cbd9c33a21aaba747b9f6346174c233aba8cd",
          "sha256": "a9274ee3a6c891c71af14d19f695a1a93c5bb4aa2bb80d20465711361f8ac546",
          "sha1": "27dceae977fe59ce0859020bc3dec68aa30cd064",
          "md5": "04c164a6c3c30d9460d11ad8b4c86ab4"
        }
      ]
    }
  ]
}
