{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-hocon",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "size": 53105,
          "sha512": "2ffdeaeff6e18496a1772bbcbb4d90b00ea0cec4ce1bbe7723edf137645c6dc65819ef0cf54906378ab0780cd6d131681f6dc24fbabadb68ffbf59a27ba044ec",
          "sha256": "2556c859be7853a1f020f74c28b69b1f836b3d6ad7b5a65c2cbfa4ccadcb0b0e",
          "sha1": "b0ab42feb46efb3087bcd4c5c17b25f5ad74bb95",
          "md5": "782564e5bc5051590be6882cd7326636"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.5.0-SNAPSHOT.jar",
          "size": 53105,
          "sha512": "2ffdeaeff6e18496a1772bbcbb4d90b00ea0cec4ce1bbe7723edf137645c6dc65819ef0cf54906378ab0780cd6d131681f6dc24fbabadb68ffbf59a27ba044ec",
          "sha256": "2556c859be7853a1f020f74c28b69b1f836b3d6ad7b5a65c2cbfa4ccadcb0b0e",
          "sha1": "b0ab42feb46efb3087bcd4c5c17b25f5ad74bb95",
          "md5": "782564e5bc5051590be6882cd7326636"
        }
      ]
    }
  ]
}
