{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-metadata-1.5.0-SNAPSHOT-all.jar",
          "url": "kotlinx-serialization-json-1.5.0-SNAPSHOT-all.jar",
          "size": 19424,
          "sha512": "65b704dd4412a03126943852f37c2fc6d62fd654795f48c08fc777bcf653a2f7dbbfa315921e103422f74f97ab14f33253476176f66298545fd4a083f8406d66",
          "sha256": "b32026f81c70520a05e843569c5b6b76366a6d869080e9631e70c404c4d9faef",
          "sha1": "553ec85de690030f19ce2150e90e2b5fa69cd9df",
          "md5": "5e8585eeebdaa9b95510733547268bdc"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-1.5.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-1.5.0-SNAPSHOT.jar",
          "size": 50652,
          "sha512": "a3980dd5aec7465ac68ca6e568291269569d4151697d06964ca889fedb84b054f891380a827c5e771633d96eba82f591e09bbdcf870fe4b511dea7de7f5367b2",
          "sha256": "9606e7967755a6c5785172113fa9cbee6eebc98f39c9eaa68cf526611a6066ef",
          "sha1": "7e137a87c8fabfc500f0559a107eace531daf3c3",
          "md5": "66c5474e44f788e6cde3f0a640007fc9"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-js/1.5.0-SNAPSHOT/kotlinx-serialization-json-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-js/1.5.0-SNAPSHOT/kotlinx-serialization-json-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-js/1.5.0-SNAPSHOT/kotlinx-serialization-json-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-js/1.5.0-SNAPSHOT/kotlinx-serialization-json-js-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-js",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-jvm/1.5.0-SNAPSHOT/kotlinx-serialization-json-jvm-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-jvm",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-jvm/1.5.0-SNAPSHOT/kotlinx-serialization-json-jvm-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-jvm",
        "version": "1.5.0-SNAPSHOT"
      }
    },
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-native/1.5.0-SNAPSHOT/kotlinx-serialization-json-native-1.5.0-SNAPSHOT.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-native",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
