name: Publish


on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: false


jobs:

  prep:
    runs-on: ubuntu-latest
    steps:
      - name: wget init.gradle.kts
        run: |
          echo "::group::wget init.gradle.kts"
          wget https://raw.githubusercontent.com/aSemy/kotlinx.serialization/master/.github/init.gradle.kts
          echo "::endgroup::"
          
          echo "::group::cat init.gradle.kts"
          cat init.gradle.kts
          echo "::endgroup::"

      - name: upload init.gradle.kts
        uses: actions/upload-artifact@v3
        with:
          name: init.gradle.kts
          path: init.gradle.kts

  publish:
    needs: prep
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - ubuntu-latest
          - macos-11
          - windows-latest
    uses: ./.github/workflows/publish_task.yml
    with:
      runs-on: ${{ matrix.os }}
