name: Publish


on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


jobs:

  publish:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-11
          - windows-latest
    uses: ./.github/workflows/publish_task.yml
    with:
      runs-on: ${{ matrix.os }}
