{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.5.0-SNAPSHOT/kotlinx-serialization-json-okio-1.5.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "nativeApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio.klib",
          "url": "kotlinx-serialization-json-okio-native-1.5.0-SNAPSHOT.klib",
          "size": 15654,
          "sha512": "cbab4eb0f349b44f37b167866c8329c59191b0728a74a9fb75d60a080d977b3024519bdfec9e3b741bfc897945776a8a38ba678483e0ddb00d9880dd73bf77a4",
          "sha256": "d6be992ec42509b31e8e97bc75ce66b32238902210f70d356fa1c2ae780e2df3",
          "sha1": "7eb881c33999f7a2b5fada81fed92870a4ff47db",
          "md5": "92cbc671f179bab8dc86224478a04c27"
        }
      ]
    }
  ]
}
